# Generated by Django 4.2 on 2025-02-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sku',
            new_name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Gene Wolfe', max_length=254),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='county',
            field=models.CharField(default='Unknown', max_length=80),
        ),
    ]
